#!/bin/bash 

socket_file=$(lsof -c emacs | grep server | grep -E -o '[^[:blank:]]*$')

if [[ $socket_file == "" ]]; then        
    # Just run Emacs (with any arguments passed to the script)
    # It would be a good idea to parse the arguments and clean/remove
    # anything emacsclient specific. 
    # (ie. -e should be --eval for emacs)
    # note that emacsclient doesn't fix these args for you either
    # when using -a / --alternate-editor

  #   if [ -n "$DISPLAY" ]; then
	# emacs "$1" &
	# else
  # 	emacs "$1"
  #   fi

else

    emacsclient $@ -n -s $socket_file
fi
